# This is a basic workflow that is manually triggered

name: Test suiteorbits
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
        numpy-version: [2.2]
        

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v4
    - name: Setup Python ${{matrix.python-version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}
    - name: Install Dependendies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --only-binary galpy galpy
        pip install numpy==${{matrix.numpy-version}}
    - name: Install Package
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest -v tests/ --cov=suiteorbits
      
      
      
